# Generated by Django 5.0 on 2024-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('symptoms', models.CharField(max_length=500)),
                ('medicines', models.CharField(max_length=500)),
                ('components', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('date', models.CharField(max_length=500)),
            ],
        ),
    ]
